version: '3'
services:
  traefik:
    container_name: srv-traefik
    image: traefik
    #command: --api --web --docker
    ports:
      - 86:80
      - 8081:8080
    networks: 
      - net-traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      - traefik.frontend.rule=Host:monitor.server.test
      - traefik.port=8080
networks:
 net-traefik:


# docker run -d \
#   -v /var/run/docker.sock:/var/run/docker.sock \
#   -v $PWD/traefik.toml:/traefik.toml \
#   -v $PWD/acme.json:/acme.json \
#   -p 80:80 \
#   -p 443:443 \
#   -l traefik.frontend.rule=Host:monitor.seu_domínio \
#   -l traefik.port=8080 \
#   --network web \
#   --name traefik \
#   traefik:1.7.2-alpine
#docker run -d -p 8080:8080 -p 80:80 --network traefik --name traefik -v $PWD/traefik.toml:/etc/traefik/traefik.toml -v /var/run/docker.sock:/var/run/docker.sock traefik
